# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jongmin Lee
title: Master Course Student
email: jongmin@jaist.ac.jp
# email_title: Email (Email title override)
phone: +81 070-8331-1473
# phone_title: Phone (Phone title override)
website: https://soybean-paste.tistory.com/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
googlescholar_username: 2dV4vDkAAAAJ
github_username:  strike137
 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Jongmin Lee, a master's student at the Cybersecurity Lab of Japan Advanced Institute of Science and Technology(JAIST), Japan. My primary research focus is on the application of Large Language Models (LLMs) in cybersecurity. In addition to my current interests in leveraging LLMs for enhancing cybersecurity and exploring the security implications of LLMs themselves, I have recently developed a deeper curiosity about the fundamental aspects of Natural Language Processing (NLP).

  - Trip to Taiwan with My Beloved Younger Brother - Summer 2023
  
  ![alt text](/images/taiwan.jpg "Taiwan")
  
content:
  - title: Education
    layout: list
    content:
      - layout: top-left
        border: weak
        title: Master of Information Science
        sub_title: Graduate School of Advanced Science and Technology, Japan Advanced Institute of Science and Technology
        caption: Ocotber 2023 - September 2025 (in progress)
        description: |
          GPA: 3.46/4.0 (in progress)
          
          Supervisor: Assistant Professor Razvan Florin Beuran          

          Second supervisor: Professor Yasuo Tan

     
 
      - layout: top-left
        border: weak
        title: Bachelor of Science, Computer Science
        sub_title: Department of Computer Science, College of Science, Korea National Open University
        caption: September 2021 - August 2023
        description: |
          GPA: 3.2/4.5 
          
          Advisor: Professor Jinuk Kim

      - layout: top-left
        border: weak
        title: Bachelor of Science, Electronic Physics (With Minor in Philosophy) 
        sub_title: Department of Electronic Physics, College of Science, Hankuk University of Foreign Studies
        caption: February 2017 - February 2021
        description: |
          GPA: 3.37/4.5
          
          Advisor: Professor Chunli Liu

          


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
                      # other value (or no value) means no border will be displayed
        title: The research on automating the construction and maintenance of secure information systems (FY 2024)
        quote: >
         セキュアな情報システムの構築と維持の自動化に関する研究(April 2024 - March 2025)
        description: | # this will include new lines to allow paragraphs
         It is a joint research program with the Japanese company NEC. The research focuses on the generation and validation of access control policies using LLMs, and I am primarily responsible for validating the source code and policies generated by the LLM. For more details, please refer to the paper that will be published in the future!

      - layout: left
        border: weak
                      # other value (or no value) means no border will be displayed
        title: The research on automating the construction and maintenance of secure information systems (FY 2023)
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Github page for project
        additional_links:
         - title:  Github page for project
           icon: fab fa-github
           url: https://github.com/cyb3rlab/RAF-AG
        quote: >
         セキュアな情報システムの構築と維持の自動化に関する研究 (October 2023 - March 2024)
        description: |
          It is a joint research program with the Japanese company NEC. Contributed to the development of RAF-AG, a framework designed to generate attack paths from Cyber Threat Intelligence (CTI) reports. My role involved collecting and analyzing multiple CTI reports, and I conducted tests using various techniques, including BERT, to improve the generation of more accurate attack graphs. This work helped enhance the framework's ability to produce high-quality, detailed attack paths for further cybersecurity analysis.
  
      - layout: left
        border: weak
                      # other value (or no value) means no border will be displayed
        title: Lattices from LDPC codes
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Github page for project
        additional_links:
         - title:  Github page for project
           icon: fab fa-github
           url: https://github.com/strike137/Lattices-from-LDPC-codes
        quote: >
         Minor Research Project for Graduation at JAIST (October 2023 - March 2024)
        description: |
          With a strong interest in information theory and coding theory, I conducted research on combining Low-Density Parity-Check (LDPC) codes with Construction A lattices to evaluate their error-correcting performance in high data-rate communication systems at BITS Lab at JAIST.
        
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Teaching Assistant
        sub_title: School of Knowledge Science, JAIST
        caption: Octomber 2024 - December 2024
        quote: >
         K228E Introduction to Knowledge Science
        description: | # this will include new lines to allow paragraphs
          As a Teaching Assistant, I contribute to knowledge co-creation by facilitating group discussions and assisting with presentations during student-led activities.

      - layout: left
        border: weak
        title: Teaching Assistant
        sub_title: Nomi International Exchange Association
        caption: April 2024 - present
        quote: >
        description: | # this will include new lines to allow paragraphs
          I am participating as a teaching assistant in English classes at various elementary schools in Nomi City in collaboration with the Nomi International Exchange Association.
          
      - layout: left
        border: weak
        title: Research Assistant
        sub_title: Cybersecurity Lab, JAIST
        caption: Octomber 2023 - present
        quote: >
        description: | # this will include new lines to allow paragraphs
          I am working as a research assistant at the Cybersecurity Lab at JAIST, conducting research on building automated security systems using LLMs.

      - layout: left
        border: weak
        title: Military Service as an Army Officer
        sub_title: Republic of Korea Army
        caption: March 2021 - June 2023
        quote: >
        description: | # this will include new lines to allow paragraphs
          After completing the Officer Candidate Course in the Republic of Korea Army, I was commissioned as an officer in the Information and Communications branch and served as a Communications Platoon Leader.

      - layout: left
        border: weak
        title: Research Assistant
        sub_title: Oxide Material and Physics Laboratory, Hankuk University of Foreign Studies
        caption: March 2018 - Febuary 2021
        quote: >
        description: | # this will include new lines to allow paragraphs
          I conducted research on photocatalysis and eco-friendly semiconductor devices for three years at the Oxide Material and Physics Laboratory at Hankuk University of Foreign Studies.

  - title: Research
    layout: list # Title for the section
    content:
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Preprint
        link: Link
        link_text: Link
        additional_links:
         - title:  Link
           icon: fab fa-github
           url: https://github.com/cyb3rlab/RAF-AG
        quote: >
        description: |
          Khang Mai, Jongmin Lee, Razvan Beuran, Ryosuke Hotchi, Sian En Ooi, Takayuki Kuroda, Yasuo Tan. (2024). RAF-AG: Report Analysis Framework for Attack Path Generation. Computer & Security. Manuscript submitted for publication.

      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Journal Paper
        link: Link
        link_text: Link
        additional_links:
         - title:  Link
           icon: fab fa-github
           url: https://pubs.rsc.org/en/content/articlelanding/2021/ra/d1ra03278j
        quote: >
        description: |
          Najmul Hasan, Daryll J. C. Dalayoan, Jaehyun Lee, Jongmin Lee, Jongseo Kim, Jong-Seong Bae, Chunli Liu. (2021). Ag0/Au0 nanocluster loaded Bi2O4 photocatalyst for methyl orange dye photodegradation. RSC Advances, Issue 43.
  
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Journal Paper
        link: Link
        link_text: Link
        additional_links:
         - title:  Link
           icon: fab fa-github
           url: https://iopscience.iop.org/article/10.1088/2053-1591/ab5e59 
        quote: >
        description: |
          Haoxuan Ma, Jongmin Lee, Namic Kwon and Chunli Liu. (2020). Effect of urea and glucose on the surface morphology and properties of CoFe2O4 nanomaterials. Materials Research Express, Volume 6, Number 12.



  - title: Language
    layout: list
    content:
      - layout: top-left
        border: weak
        title: Language
        description: |
          - Korean: Native

          - English: Fluent

          - Japanese: Conversational

          - Mandarin: Basic
          
      - layout: top-left
        border: weak
        title: Programming Language
        description: |
          - Python: Fluent

          - Matlab: Conversational

          - C: Conversational

          
  - title: A Little More About Me
    layout: text
    content:
      I would describe myself as a positive and cheerful person who likes to complete tasks efficiently. In my free time, I enjoy reading philosophy, with a recent interest in linguistic philosophy. I’m also a big fan of movies—Forrest Gump is my all-time favorite, and I admire the work of Japanese director Hirokazu Koreeda. Lately, I’ve been exploring Danish cinema as well. Besides movies, I enjoy watching baseball and soccer, and I am big fan of Orix Buffaloes. I also work part-time as an assistant in an English class at an elementary school, which has been a rewarding experience.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
